### ISSUE TITLE
Failed to train model, IndexError: list index out of range

### ISSUE THREAD

**Issue by ChunkySmoove** [SayanoAI/Comfy-RVC#12]
Cannot get past this error, using train model workflow from examples

## System Information
- **ComfyUI Version:** v0.2.2-6-gbb52934
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 10736893952
  - **VRAM Free:** 8204385368
  - **Torch VRAM Total:** 738197504
  - **Torch VRAM Free:** 5569624

Total VRAM 10240 MB, total RAM 65462 MB
pytorch version: 2.4.1+cu121
C:\Projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
unknown args: ['--windows-standalone-build']
Found GPU NVIDIA GeForce RTX 3080
__name__='Comfy-RVC.training_cli'
{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 1, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45.0, 'c_kl': 1.0, 'num_workers': 1, 'c_fm': 2.0, 'c_mfcc': 0.0, 'c_gp': 0.0, 'c_lfcc': 0.0, 'c_hd': 0.0, 'c_sts': 0.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1024, 'hop_length': 320, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': 'C:\\Projects\\ComfyUI_windows_portable\\ComfyUI\\output\\dataset\\6f9d9b8dafdaa674b21c55db4f7d04c1\\filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [20, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'experiment_dir': 'C:\\Projects\\ComfyUI_windows_portable\\ComfyUI\\output\\dataset\\6f9d9b8dafdaa674b21c55db4f7d04c1', 'model_dir': 'C:\\Projects\\ComfyUI_windows_portable\\ComfyUI\\output\\logs\\68b43b5a1fb0d595fbb5e61bdeaee6bd', 'save_every_epoch': 100, 'name': 'susan', 'total_epoch': 10, 'pretrainG': 'C:\\Projects\\ComfyUI_windows_portable\\models\\pretrained_v2\\f0G48k.pth', 'pretrainD': 'C:\\Projects\\ComfyUI_windows_portable\\models\\pretrained_v2\\f0D48k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '32k', 'if_f0': True, 'if_latest': True, 'save_every_weights': False, 'if_cache_data_in_gpu': True, 'save_best_model': True, 'best_model_threshold': 20, 'log_every_epoch': 1.0, 'model_path': 'C:\\Projects\\ComfyUI_windows_portable\\models\\RVC\\susan_32k.pth'}
C:\Projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\utils\weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
loaded pretrained C:\Projects\ComfyUI_windows_portable\models\pretrained_v2\f0G48k.pth
C:\Projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-RVC\training_cli.py:252: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(hps.pretrainG, map_location="cpu")["model"]
Process Process-1:
Traceback (most recent call last):
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-RVC\training_cli.py", line 236, in run
    _, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-RVC\lib\train\utils.py", line 188, in latest_checkpoint_path
    x = f_list[-1]
        ~~~~~~^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-RVC\training_cli.py", line 251, in run
    net_g.module.load_state_dict(
  File "C:\Projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid:
        size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 80]) from checkpoint, the shape in current model is torch.Size([256, 1, 64]).
        size mismatch for dec.ups.0.weight_v: copying a param with shape torch.Size([512, 256, 24]) from checkpoint, the shape in current model is torch.Size([512, 256, 20]).
        size mismatch for dec.ups.1.weight_v: copying a param with shape torch.Size([256, 128, 20]) from checkpoint, the shape in current model is torch.Size([256, 128, 16]).
        size mismatch for enc_q.pre.weight: copying a param with shape torch.Size([192, 1025, 1]) from checkpoint, the shape in current model is torch.Size([192, 513, 1]).
!!! Exception during processing !!! Failed to train model C:\Projects\ComfyUI_windows_portable\models\RVC\susan_32k.pth...
Traceback (most recent call last):
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 482, in train_model
    assert os.path.isfile(model_path), f"Failed to train model {model_path}..."
AssertionError: Failed to train model C:\Projects\ComfyUI_windows_portable\models\RVC\susan_32k.pth...

Prompt executed in 29.96 seconds

**Comment by ChunkySmoove** [comment]
Looks like I've solved it, needed to use 32k models when sr was set to 3d
