### ISSUE TITLE
ValueError: could not convert string to float: 'waveform'

### ISSUE THREAD

**Issue by royaiagent** [SayanoAI/Comfy-RVC#14]
using extracted coordinates
!!! Exception during processing!!! could not convert string to float: 'waveform'
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/Comfy-RVC/custom_nodes/uvr.py", line 66, in split
    hash_name = get_hash(model, agg, format, audio_to_bytes(*input_audio))
  File "/root/ComfyUI/custom_nodes/Comfy-RVC/lib/audio.py", line 184, in audio_to_bytes
    audio=np.array(audio,dtype="float32")
ValueError: could not convert string to float: 'waveform'

**Comment by SayanoAI** [comment]
Can you share your full workflow or create a simpler workflow where this error occured?

**Comment by SayanoAI** [comment]
This should be fixed with the latest updates.
