### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by bob83111** [SayanoAI/Comfy-RVC#15]
![image](https://github.com/user-attachments/assets/5ba9825e-7cf7-40fb-b943-b92e00a5784b)
![微信图片_20240911132543](https://github.com/user-attachments/assets/01963562-c02f-4780-b27f-2a167f0a54de)

Please upload a dataset!

**Comment by SayanoAI** [comment]
Create a zip file for your dataset

**Comment by bob83111** [comment]
> Create a zip file for your dataset

![image](https://github.com/user-attachments/assets/0cd26756-d55a-4d02-a0cc-185205300226)
dataset is OK, but err too

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI\ComfyUI-aki-v1.3\main.py", line 66, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
!!! Exception during processing !!! Failed to train model E:\AI\ComfyUI-aki-v1.3\models\RVC\liamcomfy_40k.pth...
Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 496, in train_model
    assert os.path.isfile(model_path), f"Failed to train model {model_path}..."
AssertionError: Failed to train model E:\AI\ComfyUI-aki-v1.3\models\RVC\liamcomfy_40k.pth...

**Comment by happy-zhangbo** [comment]
I encountered the same problem~

**Comment by happy-zhangbo** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\AI\ComfyUI\main.py", line 66, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
!!! Exception during processing !!! Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth...
Traceback (most recent call last):
  File "H:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\AI\ComfyUI\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 496, in train_model
    assert os.path.isfile(model_path), f"Failed to train model {model_path}..."
AssertionError: Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth...

**Comment by bob83111** [comment]
> Traceback (most recent call last): File "", line 1, in File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 116, in spawn_main exitcode = _main(fd, parent_sentinel) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 125, in _main prepare(preparation_data) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 236, in prepare _fixup_main_from_path(data['init_main_from_path']) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path main_content = runpy.run_path(main_path, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 289, in run_path return _run_module_code(code, init_globals, run_name, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 96, in _run_module_code _run_code(code, mod_globals, init_globals, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "H:\AI\ComfyUI\main.py", line 66, in import utils.extra_config ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package !!! Exception during processing !!! Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth... Traceback (most recent call last): File "H:\AI\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "H:\AI\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "H:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "H:\AI\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "H:\AI\ComfyUI\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 496, in train_model assert os.path.isfile(model_path), f"Failed to train model {model_path}..." AssertionError: Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth...

你是原版comfyui嘛？我用的是秋叶大佬的包

**Comment by SayanoAI** [comment]
I haven't tested this with other pre-built comfyui packages. I use miniconda to install comfyui and then use the comfyui manager to install the package.

**Comment by happy-zhangbo** [comment]
> > Traceback (most recent call last): File "", line 1, in File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 116, in spawn_main exitcode = _main(fd, parent_sentinel) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 125, in _main prepare(preparation_data) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 236, in prepare _fixup_main_from_path(data['init_main_from_path']) File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path main_content = runpy.run_path(main_path, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 289, in run_path return _run_module_code(code, init_globals, run_name, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 96, in _run_module_code _run_code(code, mod_globals, init_globals, File "D:\0.anzhuang\miniconda3\envs\comfyui\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "H:\AI\ComfyUI\main.py", line 66, in import utils.extra_config ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package !!! Exception during processing !!! Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth... Traceback (most recent call last): File "H:\AI\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "H:\AI\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "H:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "H:\AI\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "H:\AI\ComfyUI\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 496, in train_model assert os.path.isfile(model_path), f"Failed to train model {model_path}..." AssertionError: Failed to train model H:\AI\ComfyUI\models\RVC\wwww_40k.pth...
> 
> 
> 
> 你是原版comfyui嘛？我用的是秋叶大佬的包

我用的原版的 miniconda

**Comment by happy-zhangbo** [comment]
> I haven't tested this with other pre-built comfyui packages. I use miniconda to install comfyui and then use the comfyui manager to install the package.

I am in the same environment: ComfyUI, Miniconda, Python 3.10.

**Comment by bob83111** [comment]
> I haven't tested this with other pre-built comfyui packages. I use miniconda to install comfyui and then use the comfyui manager to install the package.

I mean: There is an issue with training the model. 
1. The error message is: “failed to train model e:\ai\comfyUI-aki-v1.3\models\RVC\liamcomfy_40k.pth...” 
2. The workflow uses the default rvc-model-trainer.json, with minimal modifications to the settings. 
3. The dataset is a compressed file containing multiple vocal wav files (each longer than 10 seconds).
 
![image](https://github.com/user-attachments/assets/3221cb21-fbad-4c3f-b4e2-3ea25054a54d)

**Comment by SayanoAI** [comment]
How are you starting the project? If you look at the error log, it's complaining about:
```
File "E:\AI\ComfyUI-aki-v1.3\main.py", line 66, in
import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
```
That looks like an issue with imports on line 66. Can you check what the working directory is?
Add the following code before line 66 in your main.py file, restart the server, and tell me what cwd=?
```python
import os
cwd = os.getcwd()
print(f"{cwd=}")
```

**Comment by happy-zhangbo** [comment]
> How are you starting the project? If you look at the error log, it's complaining about:
> 
> ```
> File "E:\AI\ComfyUI-aki-v1.3\main.py", line 66, in
> import utils.extra_config
> ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
> ```
> 
> That looks like an issue with imports on line 66. Can you check what the working directory is?Add the following code before line 66 in your main.py file, restart the server, and tell me what cwd=?
> 
> ```python
> import os
> cwd = os.getcwd()
> print(f"{cwd=}")
> ```


cwd is my comfyui path
![image](https://github.com/user-attachments/assets/ff776391-03c0-4e79-9376-9c193bafb549)

**Comment by bob83111** [comment]
> That looks like an issue with imports on line 66. Can you check what the working directory is? Add the following code before line 66 in your main.py file, restart the server, and tell me what cwd=?
> 
> ```python
> import os
> cwd = os.getcwd()
> print(f"{cwd=}")
> ```

**i try to add the code ,like this?**
![微信图片_20241205205524](https://github.com/user-attachments/assets/8deb0ceb-0b1b-41af-bbfc-7422d2b7d6a7)

**but the issue still exist:**

```
__before remix: shape=(9659040,), max=0.95172119140625, min=-0.990020751953125, mean=-4.222935967845842e-05 sr=44100
after remix: shape=(9659040,), max=0.9132486581802368, min=-0.949999988079071, mean=-4.052228541695513e-05, sr=44100
loading sound fname='E:\\AI\\ComfyUI-aki-v1.3\\.cache\\uvr\\77009d17f2134cdcd602c21d41989c26\\secondary.wav' audio.shape=(9659040,) audio.max()=0.91324866 audio.min()=-0.95 audio.dtype=dtype('float32') sr=44100
WARNING: No metadata found in e:\ai\comfyui-aki-v1.3\python\lib\site-packages
WARNING: No metadata found in e:\ai\comfyui-aki-v1.3\python\lib\site-packages
WARNING: No metadata found in e:\ai\comfyui-aki-v1.3\python\lib\site-packages
WARNING: No metadata found in e:\ai\comfyui-aki-v1.3\python\lib\site-packages
WARNING: No metadata found in e:\ai\comfyui-aki-v1.3\python\lib\site-packages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI\ComfyUI-aki-v1.3\main.py", line 68, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
[START] Security scan
[DONE] Security scan
[ComfyUI-Manager] Logging failed: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'comfyui.log' -> 'comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-05 20:52:33.340786
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\AI\ComfyUI-aki-v1.3\python\python.exe
** ComfyUI Path: E:\AI\ComfyUI-aki-v1.3
** Log path: E:\AI\ComfyUI-aki-v1.3\comfyui.log_

Prestartup times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
   9.1 seconds: E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

cwd='E:\\AI\\ComfyUI-aki-v1.3'
!!! Exception during processing !!! Failed to train model E:\AI\ComfyUI-aki-v1.3\models\RVC\mbgcomfy2_40k.pth...
Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 496, in train_model
    assert os.path.isfile(model_path), f"Failed to train model {model_path}..."
AssertionError: Failed to train model E:\AI\ComfyUI-aki-v1.3\models\RVC\mbgcomfy2_40k.pth..._
```
**my cwd:
 
comfyui path:     E:\AI\ComfyUI-aki-v1.3
custom nodes:   E:\AI\ComfyUI-aki-v1.3\custom_nodes
RVC path:           E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC
python path:      E:\AI\ComfyUI-aki-v1.3\Python
model path:       E:\AI\ComfyUI-aki-v1.3\models**

**Comment by SayanoAI** [comment]
Are you only having problems during training? Does inference work fine? I haven't been able to replicate your error yet. Which version of ComfyUI are you using?

**Comment by bob83111** [comment]
![image](https://github.com/user-attachments/assets/99de2e8b-c888-401b-9158-92d106d823dc)
**"There are two situations for inference. If it's the latest version of the node, it will get stuck at the Voice Changer node and won't output any results. However, if I revert to a version from July or August, everything works fine.

Right now, I can only use the version from around August 26th... I've tried every version from July to December, and none of them can train the model. Specific log:"

Let me know if you need further translation or adjustments!**
`got prompt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI\ComfyUI-aki-v1.3\main.py", line 11, in <module>
    import utils.extra_config
ModuleNotFoundError: No module named 'utils.extra_config'; 'utils' is not a package
audio.shape=(9659040,)
!!! Exception during processing !!! [Errno 2] No such file or directory: 'E:\\AI\\ComfyUI-aki-v1.3\\models\\RVC\\mbgmbgmbg.pth'
Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\custom_nodes\rvc.py", line 194, in convert
    voice_model = model()
  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\custom_nodes\rvc.py", line 444, in <lambda>
    return (lambda: get_vc(model_path, file_index), name, rvc_dataset_pipe["hubert_model"], rvc_dataset_pipe["pitch_extraction_params"])
  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\vc_infer_pipeline.py", line 199, in get_vc
    cpt = torch.load(model_path, map_location="cpu")
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AI\\ComfyUI-aki-v1.3\\models\\RVC\\mbgmbgmbg.pth'

Prompt executed in 2.62 seconds`

**Comment by aleatorydialogue** [comment]
I am having this same issue with utils not being a package. All new version from last few days for comfy. My logs look same as a previously posted version here. Inference does work, although there is some error with shard_ivf_index_centroids(...) not being found. I did have to build faiss myself so maybe a version issue with that.

**Comment by SayanoAI** [comment]
One of the latest versions of comfyui broke the ability to spawn threads inside workflow runs so I'll be merging these training features back into RVC Studio and removing the training functionality from here.

I agree, faiss (and fairseq) are a pain to work with but inference without using the index file should still work.

**Comment by aleatorydialogue** [comment]
> One of the latest versions of comfyui broke the ability to spawn threads inside workflow runs so I'll be merging these training features back into RVC Studio and removing the training functionality from here.
> 
> I agree, faiss (and fairseq) are a pain to work with but inference without using the index file should still work.

That makes sense. I actually added force spawn to comfy main.py to even get as far as I did. It was quite a struggle overall to get this to work with my setup, but yes inference is working so I'll take it. Thank you for your work on this
