### ISSUE TITLE
 No such file or directory: 'configs/32k.json'

### ISSUE THREAD

**Issue by ywaby** [SayanoAI/Comfy-RVC#16]
Cannot import /kaggle/working/ComfyUI/custom_nodes/Comfy-RVC module for custom nodes: [Errno 2] No such file or directory: 'configs/32k.json' 
err info
```
Traceback (most recent call last):
  File "/kaggle/working/ComfyUI/nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/__init__.py", line 4, in <module>
    from .custom_nodes.rvc_nodes import NODE_CLASS_MAPPINGS as rvc_nodes, NODE_DISPLAY_NAME_MAPPINGS as rvc_nodes_name
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/custom_nodes/rvc_nodes.py", line 16, in <module>
    from ..preprocessing_utils import extract_features_trainset, preprocess_trainset
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/preprocessing_utils.py", line 10, in <module>
    from .config import config
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/config.py", line 170, in <module>
    config = Config()
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/config.py", line 39, in __init__
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/config.py", line 100, in device_config
    use_fp32_config()
  File "/kaggle/working/ComfyUI/custom_nodes/Comfy-RVC/config.py", line 16, in use_fp32_config
    with open(f"configs/{config_file}", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/32k.json'
```

**Comment by ywaby** [comment]
fiexed by change path to 
```
"custom_nodes/Comfy-RVC/configs/{config_file}"
```
