### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by aurel-g** [SayanoAI/Comfy-RVC#19]
On Linux with python 3.11, I installed the requirements

```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.4.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/comfy_extras/nodes_audio.py", line 1, in <module>
    import torchaudio
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at23SavedTensorDefaultHooks11set_tracingEb

Cannot import /mnt/comfyui/app/comfy_extras/nodes_audio.py module for custom nodes: /mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at23SavedTensorDefaultHooks11set_tracingEb
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/Comfy-RVC/__init__.py", line 4, in <module>
    from .custom_nodes.rvc_nodes import NODE_CLASS_MAPPINGS as rvc_nodes, NODE_DISPLAY_NAME_MAPPINGS as rvc_nodes_name
  File "/mnt/comfyui/app/custom_nodes/Comfy-RVC/custom_nodes/rvc_nodes.py", line 14, in <module>
    from ..training_cli import train_model
  File "/mnt/comfyui/app/custom_nodes/Comfy-RVC/training_cli.py", line 35, in <module>
    from .lib.train.losses import LossBalancer, MultiScaleMelSpectrogramLoss, combined_aux_loss, generator_loss, discriminator_loss, feature_loss, gradient_norm_loss, kl_loss
  File "/mnt/comfyui/app/custom_nodes/Comfy-RVC/lib/train/losses.py", line 6, in <module>
    import torchaudio.transforms as T
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at23SavedTensorDefaultHooks11set_tracingEb

Cannot import /mnt/comfyui/app/custom_nodes/Comfy-RVC module for custom nodes: /mnt/comfyui/env/python3.11/1d453f4b0c28a95f575b63e1247484fc/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at23SavedTensorDefaultHooks11set_tracingEb

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   1.1 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/Comfy-RVC

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_audio.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by SayanoAI** [comment]
Can you try torch==2.3.1+cu118? That's the version that my torchaudio is compatible with.

**Comment by aurel-g** [comment]
It worked after recreating/updating my venv and libraries. Thanks.
